Saving automation.
Stan-Kudri/ListWatchedMoviesAndSeries pull request #19
Opened 2022-10-01 06:42 UTC by Stan-Kudri

2022-10-04 08:59 UTC, blowin requested changes
Необходимо исправить

2022-10-04 08:59 UTC, blowin commented on ListWatchedMoviesAndSeries/BoxCinemaForm.cs
> +                    GridSerializer(dgvSeries);
Название плохое, методы должны обозначать действие(глагол), а у тебя существительное (Сериализатор Грида), не имеет смысла

2022-10-04 08:59 UTC, blowin commented on ListWatchedMoviesAndSeries/BoxCinemaForm.cs
> +                    GridSerializer(dgvSeries);
Кстати, я это уже как-то писал, ты так и не исправил

2022-10-07 18:53 UTC, Stan-Kudri commented on ListWatchedMoviesAndSeries/BoxCinemaForm.cs
> +                    GridSerializer(dgvSeries);
Исправил в новом коммите.

2022-10-12 19:16 UTC, Stan-Kudri commented
Исправил все ошибки.

2022-10-14 18:49 UTC, blowin approved these changes

2022-10-14 18:57 UTC, merged